### ISSUE TITLE
[zxc(to bottom)] [ delete me] Накидано

### ISSUE THREAD

**Issue by oruchkin** [oruchkin/Async_API_sprint_3#32]
- Сервис должен проверять что пользователь не пытается зайти с токеном, который когда-либо участвовал в запросе к logout

- Access token с коротким временем жизни (10-15 минут или несколько часов) — многоразовый. Он содержит информацию о пользователе.

- Refresh token с долгим временем жизни (от нескольких дней до месяца) — одноразовый. Список актуальных refresh-токенов должен храниться в базе данных, чтобы соблюсти «одноразовость».

- Каждый час запрашивать новый рефреш и аксес токены

**Comment by GDreyV** [comment]
1. Не обязательно. На самом деле это делается только для супер критичных задач, например, когда пользователь хочет что-то удалить. Так что я бы не делал это по умолчанию, просто добавил бы вариант, что так тоже можно. У OIDC для этого есть какой-то специальный метод
2. Access token должен быть минут 5 максимум (опять же зависит от критичности сервиса), иначе мы слишком поздно узнаем, что он был отозван. Логаут не единственный вариант, что токен сломался.
3. Это уже делает сам keycloak
4. Зачем?
