### ISSUE TITLE
Добавить авторизацию в fastapi API на проверку хедера

### ISSUE THREAD

**Issue by oruchkin** [oruchkin/Async_API_sprint_3#41]
в каждом запросе приходит bearer, который должен расшифровываться и мы должны получать "current_user"

**Comment by oruchkin** [comment]
Проверять роль, если у пользователя нету Роли
то делать что-то

роли можно передавать через массив 
["admin", "moder","subscriber"]
async def protected_route(current_user: TokenData = Depends(get_current_user(["admin", "moder","subscriber"]))):
async def protected_route(current_user: TokenData = Depends(get_current_user())):

**Comment by oruchkin** [comment]
Продумайте, что делать с анонимными пользователями, которым доступно всё, что не запрещено отдельными правами.

----

если пользак анонимен то возвращть например None

**Comment by GDreyV** [comment]
Добавил
