### ISSUE TITLE
Побрейнштормить

### ISSUE THREAD

**Issue by oruchkin** [oruchkin/Async_API_sprint_3#46]
Подсказки

- [ ] Продумайте, что делать с анонимными пользователями, которым доступно всё, что не запрещено отдельными правами.

- [x] Метод проверки авторизации будет всегда нужен пользователям. Ходить каждый раз в БД — не очень хорошая идея. Подумайте, как улучшить производительность системы.

- [x] Добавьте консольную команду для создания суперпользователя, которому всегда разрешено делать все действия в системе.

- [x] Чтобы упростить себе жизнь с настройкой суперпользователя, продумайте, как сделать так, чтобы при авторизации ему всегда отдавался успех при всех запросах.

- [ ] Для реализации ограничения по фильмам подумайте о присвоении им какой-либо метки. Это потребует небольшой доработки ETL-процесса.

**Comment by GDreyV** [comment]
1 - я не очень понимаю в чем вопрос, ну просто не делать dependency для этих методов, либо сделать его optional
2, 3, 4 при нашей реализации неактуально, это все настраивается через keycloak
5 - четные/нечетные? )))
