### ISSUE TITLE
[optional] кнопка «Выйти из остальных аккаунтов»,

### ISSUE THREAD

**Issue by oruchkin** [oruchkin/Async_API_sprint_3#47]
Дополнительное задание

Реализуйте кнопку «Выйти из остальных аккаунтов», не прибегая к хранению в БД активных access-токенов.

**Comment by GDreyV** [comment]
Это уже есть, `/logout/{user_id}`

**Comment by oruchkin** [comment]
Работает благодаря самому кейклоку
