### ISSUE TITLE
Добавьте в Auth-сервис трассировку и подключите к Jaeger

### ISSUE THREAD

**Issue by GDreyV** [oruchkin/Async_API_sprint_3#60]
Добавьте в Auth-сервис трассировку и подключите к Jaeger. Для этого вам нужно добавить работу с заголовком x-request-id и отправку трассировок в Jaeger

**Comment by oruchkin** [comment]
Ссылка личная:


Кажется, у вас нет доступа
к этой странице

**Comment by GDreyV** [comment]
> Кажется, у вас нет доступа к этой странице
Это просто была ссылка на теорию для удобства
