### ISSUE TITLE
Code Review (8 спринт)

### ISSUE THREAD

**Issue by BigDeepBlue** [oruchkin/Async_API_sprint_3#76]
Добрый день! Отличная работа. Есть несколько мелочей

1. https://github.com/oruchkin/Async_API_sprint_3/blob/02144a32fa78f7ebf5890d8c496523c9c8f64403/idp/src/main.py#L75 Конфигурацию трейсера лучше вынести под настройку `if settings.enable_tracer`, чтобы была возможность его отключить, например, в тестах.
2. https://github.com/oruchkin/Async_API_sprint_3/blob/02144a32fa78f7ebf5890d8c496523c9c8f64403/idp/docker-compose.yml#L8 Порт лучше не пробрасывать в целях безопасности
3. https://github.com/oruchkin/Async_API_sprint_3/blob/02144a32fa78f7ebf5890d8c496523c9c8f64403/idp/docker-compose.yml#L3 Предполагается, что сервис высоконагруженный, поэтому стоит использовать `nginx` для оптимизации трафика
4. [можно лучше] Желательно написать тесты на API авторизации, хотя бы базовые
5. https://github.com/oruchkin/Async_API_sprint_3/blob/02144a32fa78f7ebf5890d8c496523c9c8f64403/idp/src/services/vk_client.py#L109 `HTTP`-статусы лучше не хардкодить, а получать из [констант](https://docs.python.org/3/library/http.html#http-status-codes), это немного улучшает читаемость и упрощает поиск по проекту (найти статус по названию константы, как правило, проще чем по самому числу)

**Comment by oruchkin** [comment]
- [ ]  1) Конфигурацию трейсера лучше вынести под настройку if settings.enable_tracer
- [ ]  2) убрать порт из Docker-compose
- [ ]  3) добавить nginx для idp
- [ ]  4) (опционально) добавить тесты для idp
- [ ]  5) убрать константы статусов в idp

**Comment by oruchkin** [comment]
Выполнено
pull request:
https://github.com/oruchkin/Async_API_sprint_3/pull/77
