### ISSUE TITLE
[not task] UGC заметки

### ISSUE THREAD

**Issue by oruchkin** [oruchkin/Async_API_sprint_3#79]
Пока не понятно будет ли это отдельный репозиторий (или этот же) проходим теорию, сюда накидываю заметки

Задачи:

1. - [ ]  Пользовательский рейтинг фильмов:
     - [ ]  Лайки
     - [ ]  Отзывы
2.  - [ ]  История просмотров фильмов:
3.  - [ ]  Закладки на фильмы
4.  - [ ] Список недосмотренных фильмов

---
Требования к сервису:
1. Сервис должен справляться с высокими нагрузками и выдерживать запись большого количества событий, постоянно поступающих от каждого пользователя
2. Каждый запрос должен быть однозначно соотнесён c пользователем, который его сделал, сервису понадобится аутентификация. (Полученные данные должны быть удобны для команды аналитиков. )

----
Вопросы:
1. Нужна ли интеграция в уже созданный проект или достаточно создать сервис UGC который будет в состоянии принимать данные (API)

---

Название сервиса UGC / BigData ?

----

Архитектура:
1. Если запросы от клиента будут приходить напрямую в сервис BigData, вам потребуется дублировать код проверки актуальности токена, написанный вами в AsyncAPI. При изменении его формата придётся вносить изменения в оба сервиса. 
2. Другой подход — убрать BigData за AsyncAPI, чтобы к нему проходили только валидные запросы — тоже не лишён недостатков: быстродействие системы снизится из-за сетевых взаимодействий, а большая нагрузка на BigData обернётся нагрузкой и на AsyncAPI.

**Comment by GDreyV** [comment]
Ссылка на урок: [Спринт 9/15: 9: Сервис UGC → Тема 6/7: Техно паззл → Урок 5/5: Проектное задание]( https://practicum.yandex.ru/learn/middle-python-extended/courses/22481671-2063-40fe-b236-025eed2ea014/sprints/222414/topics/1a499bba-f3d7-4689-8756-693d414c6a97/lessons/b25ca148-e201-40c9-97bc-7d3df7b9b28e/#01b0e21a-cdf1-4c11-990b-e24dd32fd841 )
Вопрос:

**Comment by GDreyV** [comment]
`Если запросы от клиента будут приходить напрямую в сервис BigData, вам потребуется дублировать код проверки актуальности токена, написанный вами в AsyncAPI. При изменении его формата придётся вносить изменения в оба сервиса.`
Это глупость какая-то, формат токена определяется стандартом
