### ISSUE TITLE
Code Review (9 спринт)

### ISSUE THREAD

**Issue by BigDeepBlue** [oruchkin/Async_API_sprint_3#93]
Добрый день! Есть несколько замечаний

1. [можно лучше] https://github.com/oruchkin/Async_API_sprint_3/blob/a1f1c3efff7e581f8e0b0820f8239efa2a56f29f/ugc/api/src/app.py#L24 `Flask` поддерживает асинхронность, можно попробовать использовать, чтобы увеличить пропускную способность https://flask.palletsprojects.com/en/latest/async-await/.  `kafka-python` тогда нужно будет заменить на асинхронный вариант (например, [aiokafka](https://aiokafka.readthedocs.io/en/stable/index.html))
2. [можно лучше] 
https://github.com/oruchkin/Async_API_sprint_3/blob/a1f1c3efff7e581f8e0b0820f8239efa2a56f29f/ugc/api/src/app.py#L23 Лучше вынести эндпоинт в соответствующую папку (например, `api`), чтобы сделать проект более структурированным, также желательно предусмотреть версионирование по аналогии с предыдущими сервисами
3. https://github.com/oruchkin/Async_API_sprint_3/blob/a1f1c3efff7e581f8e0b0820f8239efa2a56f29f/ugc/api/src/app.py#L54 `HTTP`-статусы лучше не хардкодить, а использовать соответствующие константы из [HTTPStatus](https://docs.python.org/3/library/http.html#http-status-codes), это немного увеличивает читаемость и ускоряет поиск по проекту
4. https://github.com/oruchkin/Async_API_sprint_3/blob/a1f1c3efff7e581f8e0b0820f8239efa2a56f29f/ugc/api/src/app.py#L56 Стоит обрабатывать некорректные типы и возвращать ошибку валидации, это сделает ответы API более явными
5. [можно лучше] https://github.com/oruchkin/Async_API_sprint_3/blob/a1f1c3efff7e581f8e0b0820f8239efa2a56f29f/ugc/api/src/app.py#L49 Нет необходимости инициализировать настройки на уровне обработчика, достаточно на уровне модуля
6. [можно лучше] Желательно написать тесты на API
7.  В нескольких модулях импорты не по [PEP8](https://peps.python.org/pep-0008/#imports). Можно прогнать проект через isort - https://pypi.org/project/isort/
8. Предполагается, что сервис высоконагруженный, поэтому стоит использовать `nginx` для оптимизации трафика
9. https://github.com/oruchkin/Async_API_sprint_3/blob/a1f1c3efff7e581f8e0b0820f8239efa2a56f29f/ugc/etl_service/src/clickhouse_client.py#L13 Вставку лучше делать с `backoff`, чтобы не ходить в `kafka` заново при ошибках с `clickhouse`

**Comment by oruchkin** [comment]
API:

- [ ] 1. [optional] Flask поддерживает асинхронность
- [ ] 2. [optional] Лучше вынести эндпоинт в соответствующую папку (например, api)
- [ ] 3. HTTP-статусы лучше не хардкодить, а использовать соответствующие константы из [HTTPStatus](https://docs.python.org/3/library/http.html#http-status-codes),
- [ ] 4. Стоит обрабатывать некорректные типы и возвращать ошибку валидации, это сделает ответ

- [ ] 6. [optional] Желательно написать тесты на API
- [ ] 7. использовать isort
- [ ] 8. Предполагается, что сервис высоконагруженный, поэтому стоит использовать nginx для оптимизации трафика


ETL:

- [ ] 5. Нет необходимости инициализировать настройки на уровне обработчика, достаточно на уровне модуля
- [ ] 7. использовать isort
- [ ] 9. Вставку лучше делать с backoff, чтобы не ходить в kafka заново при ошибках с clickhouse
